### ISSUE TITLE
Add --force option to overwrite existing output directory

### ISSUE THREAD

**Issue by ammaraziz** [esteinig/scrubby#24]
Scrubby stops if the output directory exists, eg this sometimes happens when snakemake pipeline breaks mid way and you restart the process. 

Add `--force` to force scrubby to overwrite existing output, or ignore it and not produce an error.

Thanks!

**Comment by esteinig** [comment]
I forgot about this Ammar - sorry for the delay. If you compile from `main` there should now be a *global* `--force` flag that applies to all commands for `scrubby` and can be used in a little bit of an odd way like this:

```
scrubby --force scrub-reads ...
```
